### ISSUE TITLE
Property 'crud' does not exist on type 'ObjectDefinitionBlock<"Query">'

### ISSUE THREAD

**Issue by robmurtagh** [graphql-nexus/nexus-plugin-prisma#332]
Hi Prisma Team, love the product and trying to work through some Proof-of-Concepts. I hope this isn't a stupid question, but I can't seem to generate `t.crud` using `prisma2 generate`.

I'm following this guide on [Database Access with Prisma 2](https://nexus.js.org/docs/database-access-with-prisma-v2), but I hit the following error message:

```
Using ts-node version 8.3.0, typescript version 3.5.2
[ERROR] 12:47:51 ⨯ Unable to compile TypeScript:
src/index.ts:16:7 - error TS2339: Property 'crud' does not exist on type 'ObjectDefinitionBlock<"Query">'.

16     t.crud.findOneFoo();
```

Both Photon and Nexus appear to have generated successfully after `prisma2 generate`, but `crud` is simply not available on the generated Nexus type/library.

The minimal example of my code is as below. Would really appreciate any insight into whats going on with this.

Thanks in advance!

#### ./package.json

```json
{
  "devDependencies": {
    "ts-node": "^8.3.0",
    "ts-node-dev": "^1.0.0-pre.40",
    "typescript": "^3.5.2"
  },
  "scripts": {
    "start": "ts-node-dev ./src/index.ts"
  },
  "dependencies": {
    "@prisma/nexus": "0.0.1",
    "graphql": "^14.4.2",
    "graphql-yoga": "^1.18.1",
    "nexus": "^0.12.0-beta.6",
    "nexus-prisma": "^0.3.7"
  }
}
```

#### ./prisma/schema.prisma

```
datasource db {
  provider = "mysql"
  url      = "mysql://..."
}

generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
}

...[INTROSPECTED MODELS HERE]
```

#### ./src/index.ts

```typescript
import { nexusPrismaPlugin } from "@generated/nexus-prisma";
import Photon from "@generated/photon";
import { makeSchema, objectType } from "@prisma/nexus";
import { GraphQLServer } from "graphql-yoga";
import { join } from "path";

const photon = new Photon();

const nexusPrisma = nexusPrismaPlugin({
  photon: (ctx) => ctx.photon,
});

const Query = objectType({
  name: "Query",
  definition(t) {
    t.crud.findOneFoo();
  },
});

const schema = makeSchema({
  types: [Query, nexusPrisma],
  outputs: {
    typegen: join(__dirname, "../generated/nexus-typegen.ts"),
    schema: join(__dirname, "/schema.graphql"),
  },
  typegenAutoConfig: {
    sources: [
      {
        source: "@generated/photon",
        alias: "photon",
      },
      {
        source: join(__dirname, "types.ts"),
        alias: "ctx",
      },
    ],
    contextType: "ctx.Context",
  },
});

const server = new GraphQLServer({
  schema,
  context: { photon },
});

server.start(() => console.log(`🚀 Server ready at http://localhost:4000`));
```

**Comment by robmurtagh** [comment]
Also, FYI: `prisma2 --version` shows:

```
prisma2@2.0.0-preview-1, binary version: 30a33bde5b1d9f79e0a48491749528da76002e24
```

**Comment by tylerjbainbridge** [comment]
Any luck with this?

**Comment by c-u-l8er** [comment]
I am following the same guide and getting the same t.crud errors plus some t.model errors.

**Comment by iherger** [comment]
In my understanding the type definitions are created when you run `makeSchema` (into `generated/nexus-typegen.ts`. Once the type definitions are there, the errors should disappear.

**Comment by tylerjbainbridge** [comment]
I can confirm that starting the server/running makeSchema on a starter project doesn't get rid of this error for me.

However- the code still works fine, it's just the types that aren't working.

**Comment by ivorpad** [comment]
Can confirm. I'm having the same issue.

tested in prisma2@2.0.0-preview-3.2

**Comment by c-u-l8er** [comment]
I looked at some of the typescript examples from photonjs.prisma.io and I was able to get things working with `ts-node-dev` although I am still getting crud and model errors when I run `ts-node` or `tsc`; running on preview 5.

**Comment by chenfanggm** [comment]
Same error here.

**Comment by chenfanggm** [comment]
Success in:
"nexus": "0.11.7"
and
"ts-node-dev": "^1.0.0-pre.40",

Fails in
"nexus": "^0.12.0-beta.6"
or
"ts-node": "8.3.0"

**Comment by mindgutter** [comment]
i have the same issue.

**Comment by marcusbrose** [comment]
You can try running the schema only with the `nexusPrisma` type. Add more types like Query afterward, when the typegen and schema was generated once. 

```
const schema = makeSchema({
  types: [nexusPrisma],
  ...
})
```

**Comment by bearcanrun** [comment]
`makeSchema` is **not** generating "nexus.ts" or "schema.graphql" files for me. `const schema` does get assigned the generated schema and when passed into the graphQL server making everything appear to be working fine.

Tried both @prisma/nexus 0.11.7  and 0.12.0-beta.6. 
Tried all the various documentation versions using `path` or just strings for outputs assignment of `schema` and `typegen`.

**Comment by bearcanrun** [comment]
I finally got the types to work. outputs is expecting an absolute path so I used:
```
outputs: {
    typegen: join(__dirname, '/generated/nexus.ts'),
    schema: join(__dirname, '/generated/schema.graphql'),
  },
```
After making sure they were generated when running `ts-node-dev`, I added import to the top of my index.ts:
```
import './generated/nexus'
```

I could then build with `tsc`

**Comment by jasonkuhrt** [comment]
Hey @robmurtagh, this should be working now. Update your deps. You can see a working example in this repo under `/example`

Ref https://github.com/prisma/nexus-prisma/issues/367#issuecomment-526921529.

**Comment by Mentioum** [comment]
This is still not working for me.

I'm still getting the same error: 

`Property 'model' does not exist on type 'ObjectDefinitionBlock<"User">'.`

Even with latest deps.

At this point I'm not even sure if I'm making mistakes or this doesn't work right now so please point me at something which definitely works.

**Comment by poulainv** [comment]
Same here : 
```
"dependencies": {
        "@types/node": "^12.7.12",
        "graphql": "^14.5.8",
        "graphql-yoga": "^1.18.3",
        "nexus": "^0.12.0-beta.14",
        "nexus-prisma": "^0.5.0"
    },
```
// package.json

```
import { makeSchema } from 'nexus'
import { nexusPrismaPlugin } from 'nexus-prisma'
import * as types from './types'
import { join } from 'path'

export const schema = makeSchema({
    types: [types, nexusPrismaPlugin({ types })],
    // prettierConfig: join(__dirname, '../../.prettierrc.json'),
    outputs: {
        schema: join(__dirname, '/generated/schema.graphql'),
        typegen: join(__dirname, '/generated/nexus.ts'),
    },
})
```
//schema.ts


I'm still getting this error:
`Property 'model' does not exist on type 'ObjectDefinitionBlock<"Profile">'`

**Comment by jasonkuhrt** [comment]
Hey @poulainv, looks like you're using the legacy config pattern. Try referring to the current examples to aid your debugging.

**Comment by poulainv** [comment]
You're right, I did not see the breaking changes. My bad. 🙏

**Comment by jasonkuhrt** [comment]
All good, let me know if any troubles arise, it is still not as easy as it should be (we're working on it 😄).

**Comment by poulainv** [comment]
Yep but when it works, dev exp is awesome ;) 
And.. for now, it works well locally but when I've deployed it on heroku I got the same error 😅

**Comment by jasonkuhrt** [comment]
@poulainv I'll setup an example for heroku soon, but for now see if the reference docs are enough: https://github.com/prisma-labs/nexus-prisma#project-setup. It actually mentions Heroku heh.

**Comment by alexichepura** [comment]
In my case the issue was misconfigured `types` field in tsconfig `compilerOptions`.

**Comment by jasonkuhrt** [comment]
Hey @alexichepura you might be interested in https://github.com/prisma-labs/nexus/issues/284 & https://github.com/prisma-labs/nexus-cli/issues/2.

**Comment by andrewdavidkay** [comment]
@jasonkuhrt is there a reason why you are using the `import *` syntax for all imports? 

```
import * as Nexus from 'nexus'
import { nexusPrismaPlugin } from 'nexus-prisma'
import * as Query from './Query'
import * as Mutation from './Mutation'
import * as Blog from './Blog'
import * as Post from './Post'
import * as User from './User'
import * as path from 'path'
```

**Comment by jasonkuhrt** [comment]
@iamandyk I personally like namespaces (ala Go) but for the data part (graphql type defs) its just a convenient pattern. For yourself, do as you please :)
